<p>
	El municipio de Tapachula es el principal centro hegemónico de las actividades y servicios de la región Soconusco, perteneciente a la región hidrológica número 23 de la cuenca del río Suchiate. La ciudad de Tapachula en las faldas de la cordillera montañosa de la Sierra Madre de Chiapas, la cual se asienta en la zona más alta de la planicie por donde pasan los ríos Coatán, Coatancito, Texcuyuapan y Cahoacán. Al interior de la ciudad se reconoce que 75.5 % de las pendientes van de  0° a 2°; el 17.3 son menores al 15 por ciento; y  sólo  el 7.2 %  en  las faldas de la Sierra Madre son pendientes superiores al 15 por ciento.
</p>
<p>
	En la ciudad de Tapachula, existen a primera vista las condiciones necesarias para poder llevar a cabo un manejo adecuado y eficiente del desarrollo urbano ya que actualmente el Municipio cuenta con un Plan de Desarrollo Urbano actualizado, elaborado recientemente, el cual proyecta a la ciudad hacia el  horizonte 2030.  Por otra parte, con el objetivo de poder atender mejor los retos prioritarios que existen en el territorio municipal. De esta manera  retos y oportunidades en el municipio son los siguientes:
</p>
<p>
	<ul style="font-size:10pt;color:#1e2f43;text-decoration:none; text-align:left;">
<li>Contrarestar los efectos de fragmentación en la ciudad, siendo en este caso el reto se encuentra en interrumpir el uso de la vía de ferrocarril dentro del tejido urbano que discurre por el tejido urbano, eliminando una barrera interna de la ciudad, y la obtención de un nuevo espacio o eje vertebrador que articule la ciudad a su interior. Esto significaría  que la liberación de esta vía, abre la oportunidad de implementar operaciones de (i) espacio público, (ii) trazos para los sistemas de transporte público, (iii) alojamiento de redes de infraestructura, etc. atendiendo las demandas específicas de la población.</li>
<li>Otro gran reto es el  equilibrar  la evidente  densidad  y condiciones de la vivienda precaria las cuales representan el 36 por ciento del parque habitacional de la ciudad. Teniendo la oportunidad de aprovechar el territorio amplio y con relieve ligero al sur de la ciudad. Las condiciones del terreno al sur de la ciudad dan muestra de un relieve prácticamente llano, con grandes reservas de suelo. Este ámbito puede alojar la expansión de la mancha urbana para el largo plazo, en el entendido de que al plazo inmediato habrá de optarse por una redensificación del tejido urbano actual y una consolidación del ámbito periurbano actual. La planificación sobre las reservas de suelo al sur de la ciudad habrá de encauzarse en vías de sostenibilidad ambiental y social</li>
<li>En la ciudad la población es vulnerable a riesgos por inundaciones,  actualmente se reconoce que las zonas urbanas más afectadas son aquellas localizadas  sobre la margen del río Coatán, derivado de los escurrimientos provocando inundaciones en áreas específicas de la ciudad. El reto en este radica en impedir el crecimiento de la ciudad principalmente hacia las serranías. Así como la oportunidad de mitigar riesgos a proceder a consolidar la correcta gestión de las aguas (residuales y de boca), ejecutando redes de abastecimiento y desagüe en los que se deberá asegurar la estanqueidad de las mismas, y el correcto mantenimiento que evite su deterioro, evitando a medida de lo posible su ubicación en zonas próximas a taludes o laderas, debiendo en dicho caso asegurarse su estanqueidad con el hormigonado de toda la sección.</li>
<li>Un sistema de transporte público ineficiente que refleja hoy día situaciones de saturación vehicular en el interior del tejido urbano consolidado, así como la ineficiencia en la prestación del servicio de transporte público. Esta situación empeora, toda vez que se mantenga la alta concentración desordenada de comercio en el interior. En este sentido, reto es entonces mejorar las condiciones accesibilidad al interior de la ciudad. Y la oportunidad se centra en mejorar el sistema de movilidad y de transporte público interviniendo  en diversos campos que dificultan la movilidad al interior buscando la peatonalización estratégica de vialidades específicas en el interior; la modernización de la flota de transporte público; la actualización del reglamento de tránsito; la planeación y ordenación del sistema de transporte público; y la dotación de redes de movilidad no motorizada a lo largo y ancho de la huella urbana, con miras a reducir emisiones y saturaciones por parte de vehículos privados y transporte público.</li>
<li>Respecto al riesgo  de  conurbación  entre  Tapachula  y  Puerto  Madero,  el reto se encuentra en romper las limitantes que  impiden o dificultan el crecimiento de los núcleos de población, ya sea por cuestiones ambientales, legales o de otra índole. El municipio de Tapachula exige la generación de proyectos que sirvan como modelo de desarrollo económico, por lo que en la actualidad no basta con generar  proyectos pequeños distribuidos en el municipio, sino apostar a  generar grandes proyectos de carácter de impulso  regional, estatal y nacional. La oportunidad es la de realizar un instrumento de ordenamiento territorial  vinculante y de visión de sostenibilidad territorial, se trata pues de definir  un  modelo de desarrollo endógeno es que el sistema productivo de un país crece aprovechando el potencial de desarrollo existente promoviendo un gran proyecto planteado como polo de desarrollo en el cual la ciudad de Tapachula y Puerto Chiapas tendrá implicaciones territoriales</li>
<li> Otro gran reto en la zona es el mitigar el riesgo por deslizamiento focalizados al margen del  río Texcuyuapan los cuales afectan aproximadamente a 333 viviendas, la oportunidad es  conseguir el espacio necesario para poder realizar una canalización que revierta dicha condición, considerando que este río atraviesa a la ciudad por su eje central, se entiende el grado de dificultad que representa la reubicación de todas las viviendas afectadas</li>
</ul>
</p>



<style>
	p{
		font-size:10pt;color:#1e2f43;text-decoration:none; width:600px; text-align:left;
		}

		</style>
